Movie_recommendation_system/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index, star

urlpatterns = [
    path('admin/', admin.site.urls),  # 后台管理系统
    path('', index),  # 首页
    path('movie/', include('movie.urls')),  # 电影推荐系统子路由
]

movie/urls.py
from django.urls import path

from . import views

app_name = 'movie'

# 子路由
urlpatterns = [
    # 默认首页
    path('', views.IndexView.as_view(), name='index'),
    # 热门电影
    path('hot', views.PopularMovieView.as_view(), name='hot'),
    # 登录
    path('login', views.LoginView.as_view(), name='login'),
    # 退出
    path('logout', views.UserLogout, name='logout'),
    # 注册
    path('register', views.RegisterView.as_view(), name='register'),
    # 分类查看
    path('tag', views.TagView.as_view(), name='tag'),
    # 搜索功能
    path('search', views.SearchView.as_view(), name='search'),
    # 电影详情页面
    path('detail/<int:pk>', views.MovieDetailView.as_view(), name='detail'),
    # 评分历史页面
    path('history/<int:pk>', views.RatingHistoryView.as_view(), name='history'),
    # 删除记录
    path('del_rec/<int:pk>', views.delete_recode, name='delete_record'),
    # 推荐页面
    path('recommend', views.RecommendMovieView.as_view(), name='recommend')
]

movie/models.py
from django.db import models
from django.db.models import Avg


# 分类信息表
class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name="type")

    class Meta:
        db_table = 'Genre'
        verbose_name = 'Movie type'
        verbose_name_plural = 'Movie type'

    def __str__(self):
        return self.name


# 电影信息表
class Movie(models.Model):
    name = models.CharField(max_length=256, verbose_name="Film title")
    imdb_id = models.IntegerField(verbose_name="imdb_id")
    time = models.CharField(max_length=256, blank=True, verbose_name="Time")
    genre = models.ManyToManyField(Genre, verbose_name="Type")
    release_time = models.CharField(max_length=256, blank=True, verbose_name="release_time")
    intro = models.TextField(blank=True, verbose_name="intro")
    director = models.CharField(max_length=256, blank=True, verbose_name="director")
    writers = models.CharField(max_length=256, blank=True, verbose_name="writers")
    actors = models.CharField(max_length=512, blank=True, verbose_name="cctors")
    # 电影和电影之间的相似度,A和B的相似度与B和A的相似度是一致的，所以symmetrical设置为True
    movie_similarity = models.ManyToManyField("self", through="Movie_similarity", symmetrical=False,
                                              verbose_name="Similar film")

    class Meta:
        db_table = 'Movie'
        verbose_name = 'Movie information'
        verbose_name_plural = 'Movie information'

    def __str__(self):
        return self.name

    # 获取平均分的方法
    def get_score(self):
        result_dct = self.movie_rating_set.aggregate(Avg('score'))  # 格式 {'score__avg': 3.125}
        try:
            result = round(result_dct['score__avg'], 1)  # 只保留一位小数
        except TypeError:
            return 0
        else:
            return result

    # 获取用户的打分情况
    def get_user_score(self, user):
        return self.movie_rating_set.filter(user=user).values('score')

    # 整数平均分
    def get_score_int_range(self):
        return range(int(self.get_score()))

    # 获取分类列表
    def get_genre(self):
        genre_dct = self.genre.all().values('name')
        genre_lst = []
        for dct in genre_dct.values():
            genre_lst.append(dct['name'])
        return genre_lst

    # 获取电影的相识度
    def get_similarity(self, k=5):
        # 默认获取5部最相似的电影的id
        similarity_movies = self.movie_similarity.all()[:k]
        return similarity_movies


# 电影相似度
class Movie_similarity(models.Model):
    movie_source = models.ForeignKey(Movie, related_name='movie_source', on_delete=models.CASCADE, verbose_name="Source film")
    movie_target = models.ForeignKey(Movie, related_name='movie_target', on_delete=models.CASCADE, verbose_name="Target film")
    similarity = models.FloatField(verbose_name="similarity")

    class Meta:
        # 按照相似度降序排序
        verbose_name = 'Movie_similarity'
        verbose_name_plural = 'Movie_similarity'


# 用户信息表
class User(models.Model):
    name = models.CharField(max_length=128, unique=True, verbose_name="User name")
    password = models.CharField(max_length=256, verbose_name="password")
    email = models.EmailField(unique=True, verbose_name="email")
    rating_movies = models.ManyToManyField(Movie, through="Movie_rating")

    def __str__(self):
        return "<USER:( name: {:},password: {:},email: {:} )>".format(self.name, self.password, self.email)

    class Meta:
        db_table = 'User'
        verbose_name = 'User name'
        verbose_name_plural = 'User name'


# 电影评分信息表
class Movie_rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=False, verbose_name="User")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, unique=False, verbose_name="Movie")
    score = models.FloatField(verbose_name="Score")
    comment = models.TextField(blank=True, verbose_name="Comment")

    class Meta:
        db_table = 'Movie_rating'
        verbose_name = 'Movie rating information'
        verbose_name_plural = 'Movie rating information'


# 最热门的一百部电影
class Movie_hot(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="Movie name")
    rating_number = models.IntegerField(verbose_name="Number of graders")

    class Meta:
        db_table = 'Movie_hot'
        verbose_name = 'hottest movie'
        verbose_name_plural = 'hottest movie'

# python manage.py makemigrations
# python manage.py migrate

movie/forms.py
from django import forms

from movie.models import User, Movie_rating


# 注册用的表单
class RegisterForm(forms.ModelForm):
    password_repeat = forms.CharField(max_length=256)

    def get_errors(self):
        errors = self.errors.get_json_data()
        errors_lst = []
        for messages in errors.values():
            for message_dict in messages:
                for key, message in message_dict.items():
                    if key == 'message':
                        errors_lst.append(message)
        return errors_lst

    # 普通验证之后的最后一层验证
    # 验证密码
    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        pwd = cleaned_data.get('password')
        password_repeat = cleaned_data.get('password_repeat')
        if pwd != password_repeat:
            raise forms.ValidationError(message='The two password entries are inconsistent！')
        return cleaned_data

    class Meta:
        model = User
        fields = ['name', 'password', 'email']


# 登录的表单
class LoginForm(forms.ModelForm):
    name = forms.CharField(max_length=128)
    remember = forms.IntegerField(required=False)

    class Meta:
        model = User
        fields = ['password']

    def get_errors(self):
        errors = self.errors.get_json_data()
        errors_lst = []
        for messages in errors.values():
            for message_dict in messages:
                for key, message in message_dict.items():
                    if key == 'message':
                        errors_lst.append(message)
        return errors_lst


# 表单验证通过后再验证分数是否为0
class CommentForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super(CommentForm, self).clean()
        score = cleaned_data.get('score')
        if score == 0:
            raise forms.ValidationError(message='The score cannot be empty！')
        else:
            return cleaned_data

    class Meta:
        # 电影评分，只记录评分和评论
        model = Movie_rating
        fields = ['score', 'comment']

movie/views.py
import os.path
import time

from django.contrib import messages
from django.db.models import Max, Count
from django.shortcuts import render, redirect, reverse
from django.views.generic import View, ListView, DetailView

from .forms import RegisterForm, LoginForm, CommentForm
from .models import User, Movie, Movie_rating, Movie_hot

BASE = os.path.dirname(os.path.abspath(__file__))


# 首页视图
class IndexView(ListView):
    model = Movie
    template_name = 'movie/index.html'
    paginate_by = 15
    context_object_name = 'movies'
    ordering = 'imdb_id'
    page_kwarg = 'p'

    # 返回前1000部电影
    def get_queryset(self):
        return Movie.objects.filter(imdb_id__lte=1000)

    # 获取上下文数据
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')  # 分页器对象
        page_obj = context.get('page_obj')  # 当前页对象
        pagination_data = self.get_pagination_data(paginator, page_obj)  # 获取分页数据
        context.update(pagination_data)  # 返回更新后的上下文数据
        return context

    # 获取分页数据
    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# 热门电影视图
class PopularMovieView(ListView):
    model = Movie_hot
    template_name = 'movie/hot.html'
    paginate_by = 15
    context_object_name = 'movies'
    page_kwarg = 'p'

    def get_queryset(self):
        # 初始化 计算评分人数最多的100部电影，并保存到数据库中，（不建议每次都运行）
        movies = Movie.objects.annotate(nums=Count('movie_rating__score')).order_by('-nums')[:100]
        for movie in movies:
            record = Movie_hot(movie=movie, rating_number=movie.nums)
            record.save()

        hot_movies = Movie_hot.objects.all().values("movie_id")
        movies = Movie.objects.filter(id__in=hot_movies).annotate(nums=Max('movie_hot__rating_number')).order_by(
            '-nums')
        return movies

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PopularMovieView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# 电影分类视图
class TagView(ListView):
    model = Movie
    template_name = 'movie/tag.html'
    paginate_by = 15
    context_object_name = 'movies'
    page_kwarg = 'p'

    # 获取数据
    def get_queryset(self):
        # 未选择分类
        if 'genre' not in self.request.GET.dict().keys() or self.request.GET.dict()['genre'] == "":
            movies = Movie.objects.all()
            return movies[100:200]
        # 有分类选择
        else:
            movies = Movie.objects.filter(genre__name=self.request.GET.dict()['genre'])
            print(movies)
            return movies[:100]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagView, self).get_context_data(*kwargs)
        if 'genre' in self.request.GET.dict().keys():
            genre = self.request.GET.dict()['genre']
            context.update({'genre': genre})
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# 搜索电影视图
class SearchView(ListView):
    model = Movie
    template_name = 'movie/search.html'
    paginate_by = 15
    context_object_name = 'movies'
    page_kwarg = 'p'

    def get_queryset(self):
        movies = Movie.objects.filter(name__icontains=self.request.GET.dict()['keyword'])
        return movies

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SearchView, self).get_context_data(*kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        context.update({'keyword': self.request.GET.dict()['keyword']})
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
            left_has_more = False
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= paginator.num_pages - around_count - 1:
            right_pages = range(current_page + 1, paginator.num_pages + 1)
            right_has_more = False
        else:
            right_pages = range(current_page + 1, current_page + 1 + around_count)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }


# 注册视图
class RegisterView(View):
    def get(self, request):
        return render(request, 'movie/register.html')

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('movie:index'))
        else:
            # 表单验证失败，重定向到注册页面
            errors = form.get_errors()
            for error in errors:
                messages.info(request, error)
            print(form.errors.get_json_data())
            return redirect(reverse('movie:register'))


# 登录视图
class LoginView(View):
    def get(self, request):
        return render(request, 'movie/login.html')

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            pwd = form.cleaned_data.get('password')
            remember = form.cleaned_data.get('remember')
            user = User.objects.filter(name=name, password=pwd).first()
            if user:
                if remember:
                    # 设置为None，则表示使用全局的过期时间
                    request.session.set_expiry(None)
                else:
                    # 立即过期
                    request.session.set_expiry(0)
                # 登录成功，在session 存储当前用户的id，作为标识
                request.session['user_id'] = user.id
                return redirect(reverse('movie:index'))

            else:
                messages.info(request, 'User name or password is incorrect!')
                return redirect(reverse('movie:login'))
        else:
            errors = form.get_errors()
            for error in errors:
                messages.info(request, error)
            return redirect(reverse('movie:login'))


# 登出，立即销毁session停止会话
def UserLogout(request):
    request.session.set_expiry(-1)
    return redirect(reverse('movie:index'))


# 电影详情视图
class MovieDetailView(DetailView):
    model = Movie
    template_name = 'movie/detail.html'
    # 上下文对象的名称
    context_object_name = 'movie'

    # 重写获取上下文方法，增加评分参数
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 判断是否登录用
        login = True
        try:
            user_id = self.request.session['user_id']
        except KeyError as e:
            login = False  # 未登录

        # 获得电影的pk（这里pk就是id）
        pk = self.kwargs['pk']

templates/movie/base.html
base:<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MoviePersona</title>
    <link rel="shortcut icon" href="{% static 'movie/favicon1.ico' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">

    <!-- 引入 Google Fonts 字体 -->
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Poppins:wght@400;500;600&family=Roboto&display=swap" rel="stylesheet">

    <script src="https://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    <style>
        body {
            font-family: 'Roboto', sans-serif;
            font-size: 15px;
            color: #333;
            line-height: 1.6;
        }

        .navbar {
            background-color: #111;
            border: none;
            box-shadow: 0 2px 8px rgba(0,0,0,0.4);
            border-radius: 0;
            padding: 10px 0;
        }

        .navbar .navbar-brand {
            font-family: 'Lobster', cursive;
            font-size: 28px;
            color: #FFD700 !important;
        }

        .navbar-nav > li > a {
            color: #fff !important;
            font-size: 16px;
            padding: 10px 15px;
            font-family: 'Poppins', sans-serif;
        }

        .navbar-nav > li > a:hover {
            background-color: #222;
            border-radius: 8px;
        }

        .navbar-form .form-control {
            border-radius: 25px;
            padding: 8px 15px;
            width: 200px;
            border: none;
            box-shadow: 0 1px 4px rgba(0,0,0,0.2);
            font-family: 'Poppins', sans-serif;
        }

        .navbar-form .btn {
            border-radius: 25px;
            background-color: #FFD700;
            border: none;
            color: #000;
            font-weight: bold;
            padding: 8px 20px;
            transition: background-color 0.3s ease;
            font-family: 'Poppins', sans-serif;
        }

        .navbar-form .btn:hover {
            background-color: #e6c200;
        }

        .btn-info {
            border-radius: 25px;
            background-color: #FFD700 !important;
            border: none;
            color: #000 !important;
            font-weight: bold;
            margin: 8px 5px;
            padding: 6px 16px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.3);
            font-family: 'Poppins', sans-serif;
        }

        .btn-info:hover {
            background-color: #e6c200 !important;
        }

        .dropdown-menu {
            border-radius: 10px;
            box-shadow: 0 3px 8px rgba(0,0,0,0.2);
        }

        .dropdown-menu > li > a {
            color: #333;
            font-family: 'Poppins', sans-serif;
        }

        .dropdown-menu > li > a:hover {
            background-color: #f5f5f5;
        }

        .mastfoot {
            font-family: 'Poppins', sans-serif;
            color: #888;
            font-size: 14px;
        }
    </style>
</head>

<body>

<!-- 导航栏 -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <!-- 响应式折叠按钮 -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar" style="background:#fff;"></span>
                <span class="icon-bar" style="background:#fff;"></span>
                <span class="icon-bar" style="background:#fff;"></span>
            </button>
            <a class="navbar-brand" href="{% url 'movie:index' %}">MoviePersona</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
            <!-- 左侧导航项 -->
            <ul class="nav navbar-nav">
                <li><a href="{% url 'movie:index' %}">Home</a></li>
                <li><a href="{% url 'movie:tag' %}">Film Genres</a></li>
                <li><a href="{% url 'movie:hot' %}">Popular films</a></li>
                {% if movie_user %}
                    <li><a href="{% url 'movie:recommend' %}">Recommendations</a></li>
                    <li><a href="{% url 'movie:history' movie_user.id %}">History</a></li>
                {% endif %}
            </ul>

            <!-- 搜索栏 -->
            <form class="navbar-form navbar-left" method="GET" action="{% url 'movie:search' %}">
                <div class="form-group">
                    <input type="search" name="keyword" class="form-control" placeholder="Search for movies" required>
                </div>
                <button type="submit" class="btn">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </form>

            <!-- 登录/注册 -->
            <ul class="nav navbar-nav navbar-right">
                {% if movie_user %}
                    <li>
                        <div class="btn-group" style="margin-top:10px">
                            <button type="button" class="btn btn-info">{{ movie_user.name }}</button>
                            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'movie:logout' %}">Log out</a></li>
                            </ul>
                        </div>
                    </li>
                {% else %}
                    <li><a href="{% url 'movie:register' %}" class="btn btn-info">Register</a></li>
                    <li><a href="{% url 'movie:login' %}" class="btn btn-info">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- 内容区 -->
{% block content %}{% endblock %}

<!-- 页脚 -->
<div class="mastfoot" style="text-align: center; margin-top: 50px; margin-bottom: 30px;">
    <div class="inner">
        <p>
            <span>Created by Chenyu Zhang, Haotian Liu, Mia Zhang, Jiayu Shen, Simin Tu, Yunqi Yang</span> &nbsp;&nbsp;
            <a href="/admin">Administrator entry</a>
        </p>
    </div>
</div>

</body>
</html>

templates/movie/history.html
{% extends 'movie/base.html' %}
{% block content %}
<script src="{% static 'layer/layer.js' %}"></script>

<style>
    body {
        background: linear-gradient(to right, #dbeafe, #bae6fd);  /* ✅ 浅蓝背景 */
        font-family: 'Segoe UI', sans-serif;
        color: #1f2937;  /* ✅ 深灰色字体 */
    }

    .container {
        padding: 40px 20px;
        max-width: 1000px;
        margin: auto;
    }

    .section-title {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 25px;
        text-align: center;
        color: #2563eb;
        text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);
    }

    .rating-card {
        display: flex;
        background: rgba(255,255,255,0.7);  /* ✅ 更亮 */
        backdrop-filter: blur(8px);
        border-radius: 16px;
        box-shadow: 0 8px 24px rgba(0,0,0,0.1);
        padding: 20px;
        margin-bottom: 30px;
        transition: transform 0.4s ease, box-shadow 0.4s ease;
    }

    .rating-card:hover {
        transform: translateY(-4px);
        box-shadow: 0 12px 28px rgba(0,0,0,0.15);
    }

    .poster {
        width: 160px;
        margin-right: 25px;
        flex-shrink: 0;
    }

    .poster img {
        width: 100%;
        border-radius: 12px;
        object-fit: cover;
        transition: transform 0.3s ease;
    }

    .poster img:hover {
        transform: scale(1.05);
    }

    .info {
        flex: 1;
    }

    .info h4 {
        margin: 0 0 10px;
        font-size: 22px;
        font-weight: bold;
        color: #1e3a8a;
    }

    .info p {
        margin: 6px 0;
        font-size: 15px;
        color: #374151;
    }

    .info strong {
        color: #2563eb;
    }

    .stars {
        color: #f59e0b;
        font-size: 18px;
        display: inline-block;
        margin-right: 10px;
    }

    .score {
        font-weight: bold;
        font-size: 16px;
        color: #2563eb;
    }

    .genre-tag {
        display: inline-block;
        background: #60a5fa;
        color: #fff;
        padding: 4px 10px;
        border-radius: 14px;
        font-size: 13px;
        margin-right: 5px;
        margin-top: 4px;
        font-weight: 600;
        transition: 0.3s;
        box-shadow: 0 2px 6px rgba(0,0,0,0.1);
    }

    .genre-tag:hover {
        background: #2563eb;
        color: #fff;
    }

    .my-comment {
        background: rgba(37, 99, 235, 0.05);
        border-left: 4px solid #2563eb;
        padding: 12px 15px;
        margin-top: 15px;
        border-radius: 10px;
        color: #1f2937;
    }

    .delete-btn {
        margin-top: 15px;
        background-color: #ef4444;
        border: none;
        color: #fff;
        border-radius: 20px;
        padding: 8px 16px;
        transition: 0.3s;
        font-weight: 500;
    }

    .delete-btn:hover {
        background-color: #dc2626;
        transform: scale(1.05);
    }

    .alert {
        background-color: #60a5fa;
        color: white;
        padding: 12px;
        border-radius: 6px;
        margin-bottom: 20px;
        text-align: center;
    }

    .layui-layer-content span {
        color: #333 !important;
    }
</style>

<div class="container">
    {% for message in messages %}
        {% if message.tags == 'info' %}
            <div class="alert" role="alert">{{ message }}</div>
        {% endif %}
    {% endfor %}
    <div class="section-title">📒 Your Scoring History</div>
</div>

<div class="container">
    {% for rating in ratings %}
        <div class="rating-card">
            <div class="poster">
                <a href="{% url 'movie:detail' rating.movie.pk %}">
                    <img src="/static/movie/poster/{{ rating.movie.imdb_id }}.jpg" alt="{{ rating.movie.name }}">
                </a>
            </div>
            <div class="info">
                <h4>{{ rating.movie.name }}</h4>
                <p class="stars">
                    {% for foo in rating.movie.get_score_int_range %}★{% endfor %}
                    <span class="score">{{ rating.movie.get_score }}</span>
                </p>
                <p>🎭 <strong>Actors:</strong> {{ rating.movie.actors }}</p>
                <p>📚 <strong>Genres:</strong>
                    {% for genre in rating.movie.get_genre %}
                        <a class="genre-tag" href="{% url 'movie:tag' %}?genre={{ genre }}">{{ genre }}</a>
                    {% endfor %}
                </p>
                <p>⏱ <strong>Duration:</strong> {{ rating.movie.time }}</p>
                <div class="my-comment">
                    <p><strong>⭐ My Score:</strong> {{ rating.score }}</p>
                    <p><strong>💬 My Comment:</strong> {{ rating.comment }}</p>
                </div>
                <button type="button" class="btn delete-btn"
                        onclick="confirm_delete('{% url 'movie:delete_record' rating.movie.id %}')">
                    🗑 Delete Comment
                </button>
            </div>
        </div>
    {% endfor %}
</div>

<script>
    function confirm_delete(url) {
        layer.open({
            title: "<span style='color:#d9534f;'>❗ Confirm Delete</span>",
            content: "<span style='font-size: 15px; color:#333;'>Are you sure you want to delete this comment? This action cannot be undone.</span>",
            icon: 5,
            btn: ["Confirm", "Cancel"],
            btnAlign: 'c',
            skin: 'layui-layer-danger',
            yes: function () {
                location.href = url;
            }
        });
    }

    window.onkeyup = function (ev) {
        const key = ev.keyCode || ev.which;
        if (key === 27) {
            layer.closeAll();
        }
    }
</script>
{% endblock %}