Movie_recommendation_system/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index, star

urlpatterns = [
    path('admin/', admin.site.urls),  # 后台管理系统
    path('', index),  # 首页
    path('movie/', include('movie.urls')),  # 电影推荐系统子路由
]

movie/urls.py
from django.urls import path

from . import views

app_name = 'movie'

# 子路由
urlpatterns = [
    # 默认首页
    path('', views.IndexView.as_view(), name='index'),
    # 热门电影
    path('hot', views.PopularMovieView.as_view(), name='hot'),
    # 登录
    path('login', views.LoginView.as_view(), name='login'),
    # 退出
    path('logout', views.UserLogout, name='logout'),
    # 注册
    path('register', views.RegisterView.as_view(), name='register'),
    # 分类查看
    path('tag', views.TagView.as_view(), name='tag'),
    # 搜索功能
    path('search', views.SearchView.as_view(), name='search'),
    # 电影详情页面
    path('detail/<int:pk>', views.MovieDetailView.as_view(), name='detail'),
    # 评分历史页面
    path('history/<int:pk>', views.RatingHistoryView.as_view(), name='history'),
    # 删除记录
    path('del_rec/<int:pk>', views.delete_recode, name='delete_record'),
    # 推荐页面
    path('recommend', views.RecommendMovieView.as_view(), name='recommend')
]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MoviePersona</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <style>
        /*
         * Globals
         */

        /* Links */
        a,
        a:focus,
        a:hover {
            color: #fff;
        }

        /* Custom default button */
        .btn-default,
        .btn-default:hover,
        .btn-default:focus {
            color: #333;
            text-shadow: none;
            background-color: #fff;
            border: 1px solid #fff;
        }


        /*
         * Base structure
         */

        html,
        body {
            height: 100%;
            background-color: #333;
            background-image: url('/static/pexels-cottonbro-4881679.jpg'); /* 设置背景图片 */
            background-size: cover; /* 确保图片覆盖整个页面 */
            background-position: center; /* 图片居中 */
            background-repeat: no-repeat; /* 防止图片重复 */
            color: #fff;
            text-align: center;
            text-shadow: 0 1px 3px rgba(0, 0, 0, .5);
            font-size: 18px;
            font-family: 'Irish Grover', sans-serif; /* 使用艺术字体 */
        }

        /* Extra markup and styles for table-esque vertical and horizontal centering */
        .site-wrapper {
            display: table;
            width: 100%;
            height: 100%; /* For at least Firefox */
            min-height: 100%;
            -webkit-box-shadow: inset 0 0 100px rgba(0, 0, 0, .5);
            box-shadow: inset 0 0 100px rgba(0, 0, 0, .5);
        }

        .site-wrapper-inner {
            display: table-cell;
            vertical-align: top;
        }

        .cover-container {
            margin-right: auto;
            margin-left: auto;
        }

        /* Padding for spacing */
        .inner {
            padding: 30px;
        }

        h1.cover-heading {
        font-family: 'Lobster', cursive;
        font-size: 60px;
        color: #FFD700;
        letter-spacing: 1px;
        text-shadow: none;
        text-transform: none;
    }


        p.lead {
            font-size: 22px;  /* 更大段落字体 */
        }

        /*
         * Header
         */
        .masthead-brand {
            margin-top: 10px;
            margin-bottom: 10px;
        }

        .masthead-nav > li {
            display: inline-block;
        }

        .masthead-nav > li + li {
            margin-left: 20px;
        }

        .masthead-nav > li > a {
            padding-right: 0;
            padding-left: 0;
            font-size: 16px;
            font-weight: bold;
            color: #fff; /* IE8 proofing */
            color: rgba(255, 255, 255, .75);
            border-bottom: 2px solid transparent;
        }

        .masthead-nav > li > a:hover,
        .masthead-nav > li > a:focus {
            background-color: transparent;
            border-bottom-color: #a9a9a9;
            border-bottom-color: rgba(255, 255, 255, .25);
        }

        .masthead-nav > .active > a,
        .masthead-nav > .active > a:hover,
        .masthead-nav > .active > a:focus {
            color: #fff;
            border-bottom-color: #fff;
        }

        @media (min-width: 768px) {
            .masthead-brand {
                float: left;
            }

            .masthead-nav {
                float: right;
            }
        }

        /*
         * Footer
         */

        .mastfoot {
            color: #999; /* IE8 proofing */
            color: rgba(255, 255, 255, .5);
        }

    </style>
</head>

<body>

<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="masthead clearfix">
                <div class="inner">
                </div>
            </div>
            <div class="inner cover">
                <h1 class="cover-heading">MoviePersona</h1>
                <p class="lead">Film recommendation system for UK University students</p>
                <p class="lead">
                    <a href="{% url 'movie:index' %}" class="btn btn-lg btn-default">Access system</a>
                </p>
            </div>
            <div class="mastfoot">
                <div class="inner">
                    <p>
                        <span>Create by Chenyu Zhang,Haotian Liu,Mia Zhang,Jiayu Shen,Simin Tu,Yunqi
Yang</span>&nbsp;&nbsp;
                        <a href="/admin">Administrator entry</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>